module.exports = {
  boolean: require('./boolean'),
  integer: require('./integer'),
  string: require('./string'),
  decimal: require('./decimal'),
  uri: require('./uri'),
  base64Binary: require('./base64Binary'),
  instant: require('./instant'),
  date: require('./date'),
  dateTime: require('./dateTime'),
  time: require('./time'),
  code: require('./code'),
  oid: require('./oid'),
  id: require('./id'),
  markdown: require('./markdown'),
  unsignedInt: require('./unsignedInt'),
  positiveInt: require('./positiveInt'),
};
